from pydantic import BaseModel, Field
from typing import Optional

class CallDataRecord(BaseModel):
    CallID: int
    MediaFileName: Optional[str]
    FechaHoraInicio: Optional[str]
    FechaHoraFin: Optional[str]
    Duracion: Optional[str]
    ANI: Optional[int]
    DNIS: Optional[str]
    Extension: Optional[str]
    LoginIDTelefonia: Optional[str]
    CallDirection: Optional[str]
    RutaGrabacion: Optional[str]
    FechaEjecucionInsertGrabador: Optional[str]
    FechaReferenciaDatos: Optional[str]
    FechaEjecucionInsertAsesor: Optional[str]
    IdPais: Optional[int]
    Cliente: Optional[str]
    CodigoPrograma: Optional[str]
    Programa: Optional[str]
    CodigoServicio: Optional[int]
    NombreServicio: Optional[str]
    CodFinanciero: Optional[str]
    CECO: Optional[str]
    NombreArea: Optional[str]
    PBX: Optional[str]
    IDTelefonia: Optional[str]
    IDEmpleado: Optional[str]
    NombreEmpleado: Optional[str]
    Local: Optional[str]
    CargoEmpleado: Optional[str]
    IDSupervisor: Optional[str]